overwrite: true
schema: "http://localhost:7000/"
documents: "src/gql/*.ts"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
